// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://invhbfopwqnwtdxfiima.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImludmhiZm9wd3Fud3RkeGZpaW1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODgyMTAsImV4cCI6MjA3MjY2NDIxMH0.VRwsVtzgR7HWw5Pm5U9MVXlQ0kixpQO7ayQzhLHclho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});